#######################################################################
# Wiki.js - CONFIGURATION                                             #
#######################################################################
# Full explanation + examples in the documentation:
# https://docs.requarks.io/wiki/install

# ---------------------------------------------------------------------
# Port the main server should listen to
# ---------------------------------------------------------------------

port: 80

# ---------------------------------------------------------------------
# Data Directories
# ---------------------------------------------------------------------

paths:
  repo: ./repo
  data: ./data

# ---------------------------------------------------------------------
# Database
# ---------------------------------------------------------------------

db:
  host: localhost
  port: 5432
  user: wikijs
  pass: wikijsrocks
  db: wiki

# ---------------------------------------------------------------------
# Redis
# ---------------------------------------------------------------------

redis:
  host: localhost
  port: 6379
  db: 0
  password: null

# ---------------------------------------------------------------------
# Background Workers
# ---------------------------------------------------------------------
# Leave 0 for auto based on CPU cores

workers: 0

# ---------------------------------------------------------------------
# High Availability
# ---------------------------------------------------------------------
# Read the docs BEFORE changing these settings!

ha:
  nodeuid: primary
  readonly: false
